// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtm_q5IFJbov7m6uB5HN5B5ltgpF2wPT8',
    appId: '1:1018462753751:web:6a528cd404741caf957192',
    messagingSenderId: '1018462753751',
    projectId: 'fir-flutter-codelab-674df',
    authDomain: 'fir-flutter-codelab-674df.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-674df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGdAzZMR2mqsc5_OsJ2keB1ROTN9MI7pc',
    appId: '1:1018462753751:android:0d2d32a7477361cf957192',
    messagingSenderId: '1018462753751',
    projectId: 'fir-flutter-codelab-674df',
    storageBucket: 'fir-flutter-codelab-674df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_RpkV57j-Qi7Bg6RpjlqV-31s9Wzsck',
    appId: '1:1018462753751:ios:d58d6b6b9963cbc6957192',
    messagingSenderId: '1018462753751',
    projectId: 'fir-flutter-codelab-674df',
    storageBucket: 'fir-flutter-codelab-674df.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_RpkV57j-Qi7Bg6RpjlqV-31s9Wzsck',
    appId: '1:1018462753751:ios:d58d6b6b9963cbc6957192',
    messagingSenderId: '1018462753751',
    projectId: 'fir-flutter-codelab-674df',
    storageBucket: 'fir-flutter-codelab-674df.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
